//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Login.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HostelData
    {
        public int RollNo { get; set; }
        public string Name { get; set; }
        public string RoomNo { get; set; }
        public string HostelName { get; set; }
        public string ContactNo { get; set; }
    }
}
